project:
  type: website
  output-dir: docs

website:
  title: "SLE-autoantibody-prediction"
  description: "Microarray analysis of autoantibodies can identify future Systemic Lupus Erythematosus patients"
  repo-url: https://github.com/umcu/SLE-autoantibody-prediction
  repo-actions: [source, issue]
  sidebar:
    title: "SLE-autoantibody-prediction"
    logo: https://cdn.worldvectorlogo.com/logos/umc-utrecht-1.svg
    style: "floating"
    contents: 
      - notebooks/preprocess.ipynb
      - notebooks/projection.ipynb
      - section: "Prediction"
        contents:
          - notebooks/Main Results.ipynb
          - notebooks/SLE Versus BBD.ipynb
          - notebooks/SLE Versus nonIMID.ipynb
          - notebooks/Nefritis Versus non-nefritis.ipynb
  page-footer: 
    left: 
      - text: "Copyright 2022, UMC Utrecht (MIT License)"
        href: https://github.com/umcu/SLE-autoantibody-prediction/blob/main/LICENSE
    right:
      - icon: link
        href: https://www.umcutrecht.nl
      - icon: github
        href: https://github.com/umcu
      - icon: twitter
        href: https://twitter.com/UMCU_Intl
        
author: 
  - name: Leon C. Reteig
    affiliation: University Medical Center Utrecht

format:
  html:
    css: styles.css
    toc: true
    anchor-sections: true
    code-tools:
      toggle: false
      source: repo