name: SLE
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.5
  - pandas=1.1.0
  - scikit-learn=0.23.2
  - matplotlib=3.1.3
  - jupyterlab=2.1.0
  - py-xgboost=0.90
  - hyperopt=0.2.4
  - shap=0.35.0
  - pyreadstat=1.0.0
  - feather-format=0.4.1
  - seaborn=0.10.1
  - umap-learn=0.4.6
  - pandas-profiling=2.4.0
  - statsmodels=0.11.1
  - ipywidgets=7.5.1
  - pip
  - pip:
    - umap-learn[plot]
    - dabl # requires newer version of sklearn than stability-selection
    - openpyxl==3.0.7
    - lxml
    - git+https://github.com/lcreteig/stability-selection.git@joblib