name: SLE
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.5
  - pandas
  - scikit-learn
  - matplotlib
  - jupyterlab
  - py-xgboost
  - hyperopt
  - shap
  - pyreadstat
  - feather-format