name: SLE
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.5
  - pandas
  - scikit-learn
  - matplotlib
  - jupyterlab
  - py-xgboost
  - hyperopt
  - shap
  - pyreadstat
  - feather-format
  - seaborn
  - umap-learn
  - pandas-profiling
  - statsmodels
  - ipywidgets
  - pip
  - pip:
    - dabl
    - git+https://github.com/lcreteig/stability-selection.git@joblib